version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=new_password
      - POSTGRES_DB= Jobs
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data