name: Automated Job Portal

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5'
    
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  pull-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::150031404574:role/github
        role-duration-seconds: 3600 # the ttl of the session, in seconds.
        aws-region: eu-west-3 # use your region here.

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - id: repo 
      name: Repo Checkout
      uses: actions/checkout@v2
      
    - id: python
      name: Python Setup & Packages Installation
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install -r auto_req.txt
    
    - name: Set environment variables and run jupyter     
      env:
       DB_HOST: ${{ secrets.DB_HOST }}
       DB_NAME: ${{ secrets.DB_NAME }}
       DB_PORT: ${{ secrets.DB_PORT }}
       DB_USER: ${{ secrets.DB_USER }}
       DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      
      run: jupyter execute test.ipynb
      shell: bash   

 # Add new files in folder, commit along with other modified files, push
    - id: commit
      name: Commit files
      run:
        git config --local user.name actions-user

        git config --local user.email "actions@github.com"

        git add *

        git commit -am "scheduled run succesful"

        git push origin main

      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}

        username: github-actions
