name: Pull and run container

on:
  workflow_dispatch:

jobs:
  pull-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker
      uses: actions/setup-docker@v2

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Pull container image
      run: docker pull asteriosman/jobs:latest

    - name: Run container
      run: docker run -d --name jobs-container -p 80:80 asteriosman/jobs:latest
